sudo: required
language: c
script: make runtest
install: true
compiler:
  - clang
  - gcc
notifications:
  webhooks:
    urls: 
     - https://webhooks.gitter.im/e/64efb2a578d19a3573aa
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

